references:
  envoy-build-image: &envoy-build-image
    envoyproxy/envoy-build:latest

version: 2
jobs:
  build:
    docker:
      - image: *envoy-build-image
    resource_class: xlarge
    steps:
      - checkout
      - run: ci/do_ci.sh build
  test:
    docker:
      - image: *envoy-build-image
    resource_class: xlarge
    steps:
      - checkout
      - run: ci/do_ci.sh test
  clang_tidy:
    docker:
      - image: *envoy-build-image
    resource_class: xlarge
    steps:
      - checkout
      - run: ci/do_ci.sh clang_tidy

workflows:
  version: 2
  all:
    jobs:
      - build
      - test
      - clang_tidy
